name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Copy build folder
        run: |
          mkdir build
          cp -R dist/* build/
      - name: Commit build changes
        run: |
          git config --global user.name "fuadariqoh"
          git config --global user.email "fuadariqoh@gmail.com"
          git add build/
          git commit -m "Add build folder"
          git push origin master
